[general]
use_middle_proxy = true
log_level = "normal"

[general.modes]
classic = false
secure = false
tls = true

[general.links]
show = "*"
public_host = "__SERVER_HOST__"
public_port = __PROXY_PORT__

[server]
port = 443

[server.api]
enabled = true
listen = "0.0.0.0:9091"
whitelist = ["127.0.0.1/32", "::1/128", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
read_only = false

[[server.listeners]]
ip = "0.0.0.0"

[censorship]
tls_domain = "__TLS_DOMAIN__"
mask = true
tls_emulation = true
tls_front_dir = "tlsfront"

[access.users]
shop_bootstrap = "__SHOP_BOOTSTRAP_SECRET__"
